import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import { QueryClientProvider } from "@tanstack/react-query";
import { RouterProvider, createBrowserRouter } from "react-router";

import ActiveAndPassiveAbilities from "./components/ActiveAndPassiveAbilities/ActiveAndPassiveAbilities";
import { Items } from "./components/Items";
import { Main } from "./components/Main";
import { NotFound } from "./components/NotFound";
import { RouteError } from "./components/RouteError";
import { Skills } from "./components/Skills/Skills";
import { Spells } from "./components/Spells";
import { CharacterLayout, Home, Root } from "./components/App";
import { Account } from "./components/Auth/Account";
import { Login } from "./components/Auth/Login";
import { RequireAuth } from "./components/Auth/RequireAuth";
import { SignUp } from "./components/Auth/SignUp";

import "./index.css";
import { queryClient } from "./store/api";
// Register the PWA service worker generated by vite-plugin-pwa
import { registerSW } from 'virtual:pwa-register';


const router = createBrowserRouter([
  {
    path: "/",
    element: <Root />,
    errorElement: <RouteError />,
    children: [
      { path: "login", element: <Login /> },
      { path: "signup", element: <SignUp /> },
      {
        element: <RequireAuth />,
        children: [
          { index: true, element: <Home /> },
          { path: "account", element: <Account /> },
          {
            path: "characters/:characterId",
            element: <CharacterLayout />,
            children: [
              { index: true, element: <Main /> },
              { path: "skills", element: <Skills /> },
              { path: "items", element: <Items /> },
              { path: "spells", element: <Spells /> },
              { path: "abilities", element: <ActiveAndPassiveAbilities /> },
            ],
          },
        ],
      },
      { path: "*", element: <NotFound /> },
    ],
  },
]);

const container = document.getElementById("root");
const root = createRoot(container!);

root.render(
  <StrictMode>
    <QueryClientProvider client={queryClient}>
      <RouterProvider router={router} />
    </QueryClientProvider>
  </StrictMode>,
);

// If you want your app to work offline and load faster, you can change
// unregister() to register() below. Note this comes with some pitfalls.
// Learn more about service workers: https://bit.ly/CRA-PWA
// Register the service worker in production so the app can work offline and be a PWA.
// Uses the Vite built base URL via import.meta.env.BASE_URL inside serviceWorker module.
// register the PWA service worker with immediate update strategy
registerSW({ immediate: true });
